# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Monster.delete_all
Plane.delete_all
Climate.delete_all
Terrain.delete_all

owlbear = Monster.create!(
    name:'Owlbear',
    cr:4,
    xp:1200,
    description:'An amalgam of fur and feathers, this bizarre half-bear, half-owl monstrosity raises its huge, ursine claws in anger.',
    race_class_level:'',
    align_size_type:'N Large magical beast',
    init:'+5',
    senses:'darkvision 60 ft., low-light vision, scent; Perception +12',
    aura:'',
    ac:'15, touch 10, flat-footed 14 (+1 Dex, +5 natural, –1 size)',
    hp:'47 (5d10+20)',
    fort:'+10',
    ref:'+5',
    will:'+2',
    defensive_abilities:'',
    dr:'',
    immune:'',
    resist:'',
    sr:'',
    weaknesses:'',
    speed:'30 ft.',
    melee:'2 claws +8 (1d6+4 plus grab), bite +8 (1d6+4)',
    ranged:'',
    space:'10 ft.',
    reach:'5 ft.',
    special_attacks:'',
    spell_like_abilities:'',
    spells_known:'',
    spells_prepared:'',
    str:'19',
    dex:'12',
    con:'18',
    int:'2',
    wis:'12',
    cha:'10',
    base_atk:'+5',
    cmb:'+10 (+14 grapple)',
    cmd:'21 (25 vs. trip)',
    feats:'Improved Initiative, Great Fortitude, Skill Focus (Perception)',
    skills:'Perception +12',
    racial_modifiers:'',
    languages:'',
    sq:'',
    env:'temperate forests',
    organization:'solitary, pair, or pack (3–8)',
    treasure:'incidental',
    special_abilities:'',
    more_info_link:'http://www.d20pfsrd.com/bestiary/monster-listings/magical-beasts/owlbear'
)
ghoul = Monster.create!(
    name:'Ghoul',
    cr:1,
    xp:400,
    description:'This humanoid creature has long, sharp teeth, and its pallid flesh is stretched tightly over its starved frame.',
    race_class_level:'',
    align_size_type:'CE Medium undead',
    init:'+2',
    senses:'darkvision 60 ft.; Perception +7',
    aura:'',
    ac:'14, touch 12, flat-footed 12 (+2 Dex, +2 natural)',
    hp:'13 (2d8+4)',
    fort:'+2',
    ref:'+2',
    will:'+5',
    defensive_abilities:'channel resistance +2; Immune undead traits',
    dr:'',
    immune:'',
    resist:'',
    sr:'',
    weaknesses:'',
    speed:'30 ft.',
    melee:'bite +3 (1d6+1 plus disease and paralysis) and 2 claws +3 (1d6+1 plus paralysis)',
    ranged:'',
    space:'',
    reach:'',
    special_attacks:'paralysis (1d4+1 rounds, DC 13, elves are immune to this effect)',
    spell_like_abilities:'',
    spells_known:'',
    spells_prepared:'',
    str:'13',
    dex:'15',
    con:'-',
    int:'13',
    wis:'14',
    cha:'14',
    base_atk:'+1',
    cmb:'+2',
    cmd:'14',
    feats:'Weapon Finesse',
    skills:'Acrobatics +4, Climb +6, Perception +7, Stealth +7, Swim +3',
    racial_modifiers:'',
    languages:'Common',
    sq:'',
    env:'any land',
    organization:'solitary, gang (2–4), or pack (7–12)',
    treasure:'standard',
    special_abilities:'Disease (Su): Ghoul Fever: Bite—injury; save Fort DC 13; onset 1 day; frequency 1/day; effect 1d3 Con and 1d3 Dex damage; cure 2 consecutive saves. The save DC is Charisma-based.',
    more_info_link:'http://www.d20pfsrd.com/bestiary/monster-listings/undead/ghoul'
)
ooze = Monster.create!(
    name:'Ooze (Gelatinous Cube)',
    cr:3,
    xp:800,
    description:'Bits of broken weapons, coins, and a partially digested skeleton are visible inside this quivering cube of slime.',
    race_class_level:'',
    align_size_type:'N Large ooze',
    init:'-5',
    senses:'blindsight 60 ft.; Perception –5',
    aura:'',
    ac:'4, touch 4, flat-footed 4 (–5 Dex, –1 size)',
    hp:'50 (4d8+32)',
    fort:'+9',
    ref:'-4',
    will:'-4',
    defensive_abilities:'',
    dr:'',
    immune:'electricity, ooze traits',
    resist:'',
    sr:'',
    weaknesses:'',
    speed:'15 ft.',
    melee:'slam +2 (1d6 plus 1d6 acid)',
    ranged:'',
    space:'10 ft.',
    reach:'5 ft.',
    special_attacks:'engulf, paralysis',
    spell_like_abilities:'',
    spells_known:'',
    spells_prepared:'',
    str:'10',
    dex:'1',
    con:'26',
    int:'-',
    wis:'1',
    cha:'1',
    base_atk:'+3',
    cmb:'+4',
    cmd:'9 (cannot be tripped)',
    feats:'',
    skills:'',
    racial_modifiers:'',
    languages:'',
    sq:'transparent',
    env:'any underground',
    organization:'solitary',
    treasure:'incidental',
    special_abilities:'Acid (Ex), Engulf (Ex), Paralysis (Ex), Transparent (Ex)',
    more_info_link:'http://www.d20pfsrd.com/bestiary/monster-listings/oozes/gelatinous-cube'
)
shark = Monster.create!(
    name:'Common Shark',
    cr:2,
    xp:600,
    description:'This blue shark"s fins slice through the water, its black eyes rolling and its gaping jaws showing countless teeth.',
    race_class_level:'',
    align_size_type:'N Large animal (aquatic)',
    init:'+5',
    senses:'blindsense 30 ft., keen scent; Perception +8',
    aura:'',
    ac:'14, touch 10, flat-footed 13 (+1 Dex, +4 natural, –1 size)',
    hp:'22 (4d8+4)',
    fort:'+7',
    ref:'+5',
    will:'+2',
    defensive_abilities:'',
    dr:'',
    immune:'',
    resist:'',
    sr:'',
    weaknesses:'',
    speed:'swim 60 ft.',
    melee:'bite +5 (1d8+4)',
    ranged:'',
    space:'10 ft.',
    reach:'5 ft.',
    special_attacks:'',
    spell_like_abilities:'',
    spells_known:'',
    spells_prepared:'',
    str:'17',
    dex:'12',
    con:'13',
    int:'1',
    wis:'12',
    cha:'2',
    base_atk:'+3',
    cmb:'+7',
    cmd:'18',
    feats:'Great Fortitude, Improved Initiative',
    skills:'Perception +8, Swim +11',
    racial_modifiers:'',
    languages:'',
    sq:'',
    env:'any ocean',
    organization:'solitary, pair, school (3–6), or pack (7–13)',
    treasure:'none',
    special_abilities:'',
    more_info_link:'http://www.d20pfsrd.com/bestiary/monster-listings/animals/shark/shark'
)
shoggoth = Monster.create!(
    name:'Shoggoth',
    cr:19,
    xp:204800,
    description:'This immense mound of black slime thunders forward, eyes and mouths and even stranger things forming in its heaving bulk.',
    race_class_level:'',
    align_size_type:'CN Huge ooze (aquatic)',
    init:'+11',
    senses:'all-around vision, darkvision 120 ft., low-light vision, scent, tremorsense 60 ft.; Perception +33',
    aura:'',
    ac:'33, touch 15, flat-footed 26 (+7 Dex, +18 natural, –2 size)',
    hp:'333 (23d8+230); fast healing 10',
    fort:'+19',
    ref:'+14',
    will:'+15',
    defensive_abilities:'',
    dr:'10/—',
    immune:'blindness, charm effects, cold, deafness, ooze traits, sonic',
    resist:'acid 20, electricity 20, fire 20',
    sr:'30',
    weaknesses:'',
    speed:'50 ft., climb 30 ft., swim 50 ft.',
    melee:'4 slams +30 (3d6+15/19–20 plus grab) ',
    ranged:'',
    space:'15 ft.',
    reach:'30 ft.',
    special_attacks:'constrict (3d6+15), maddening cacophony, engulf (4d6+22 bludgeoning damage plus 8d6 acid damage, AC 19, hp 33), trample (4d8+15, DC 36)',
    spell_like_abilities:'',
    spells_known:'',
    spells_prepared:'',
    str:'40',
    dex:'24',
    con:'31',
    int:'5',
    wis:'22',
    cha:'13',
    base_atk:'+17',
    cmb:'+34 (+39 grapple)',
    cmd:'51 (cannot be tripped)',
    feats:'Blind-Fight, Cleave, Combat Reflexes, Critical Focus, Great Cleave, Great Fortitude, Improved Critical (slam), Improved Initiative, Improved Sunder, Iron Will, Power Attack, Staggering Critical',
    skills:'Climb +23, Perception +33, Swim +23',
    racial_modifiers:'+4 Perception',
    languages:'Aklo',
    sq:'amphibious',
    env:'cold aquatic or underground',
    organization:'solitary or tide (2–6)',
    treasure:'standard',
    special_abilities:'All-Around Vision (Ex), Maddening Cacophony (Su), Engulf (Ex)',
    more_info_link:'http://www.d20pfsrd.com/bestiary/monster-listings/oozes/shoggoth'
)
aasimar = Monster.create!(
    name:'Aasimar',
    cr:0.5,
    xp:200,
    description:'This supernaturally beautiful woman looks human, yet emanates a strange sense of calm and benevolence.',
    race_class_level:'Aasimar cleric 1',
    align_size_type:'NG Medium outsider (native)',
    init:'+0',
    senses:'darkvision 60 ft.; Perception +5',
    aura:'',
    ac:'15, touch 10, flat-footed 15 (+5 armor)',
    hp:'11 (1d8+3)',
    fort:'+4',
    ref:'+0',
    will:'+5',
    defensive_abilities:'',
    dr:'',
    immune:'',
    resist:'acid 5, cold 5, electricity 5',
    sr:'',
    weaknesses:'',
    speed:'30 ft. (20 ft. in armor)',
    melee:'heavy mace –1 (1d8–1)',
    ranged:'light crossbow +0 (1d8/19–20)',
    space:'',
    reach:'',
    special_attacks:'channel positive energy (5/day, 1d6, DC 12); rebuke death (1d4+1, 6/day); touch of good (6/day)',
    spell_like_abilities:'(CL 1st) - 1/day–daylight',
    spells_known:'',
    spells_prepared:'(CL 1st) - 1st–bless, command (DC 14), protection from evilD; 0th (at will)–detect magic, guidance, stabilize; D domain spell; Domains Good, Healing',
    str:'8',
    dex:'10',
    con:'14',
    int:'13',
    wis:'17',
    cha:'14',
    base_atk:'+0',
    cmb:'-1',
    cmd:'9',
    feats:'Turn Undead',
    skills:'Diplomacy +8, Heal +7, Knowledge (religion) +5',
    racial_modifiers:'+2 Diplomacy, +2 Perception',
    languages:'Celestial, Common, Draconic',
    sq:'',
    env:'any land',
    organization:'solitary, pair, or team (3–6)',
    treasure:'NPC gear (scale mail, heavy mace, light crossbow with 10 bolts, other treasure)',
    special_abilities:'',
    more_info_link:'http://www.d20pfsrd.com/bestiary/monster-listings/outsiders/aasimar'
)
archon = Monster.create!(
    name:'Trumpet Archon',
    cr:14,
    xp:38400,
    description:'Lithe and beautiful, with skin the color of marble, this being hovers upon powerful, white wings and radiates a sense of serenity.',
    race_class_level:'',
    align_size_type:'LG Medium outsider (archon, extraplanar, good, lawful)',
    init:'+7',
    senses:'darkvision 60 ft., low-light vision; Perception +22',
    aura:'aura of menace (DC 22), magic circle against evil',
    ac:'27, touch 13, flat-footed 24 (+3 Dex, +14 natural; +2 deflection vs. evil)',
    hp:'175 (14d10+98)',
    fort:'+16',
    ref:'+9',
    will:'+14; +4 vs. poison, +2 resistance vs. evil',
    defensive_abilities:'',
    dr:'10/evil',
    immune:'electricity, petrification',
    resist:'',
    sr:'25',
    weaknesses:'',
    speed:'40 ft., fly 90 ft. (good)',
    melee:'+4 greatsword +23/+18/+13 (2d6+11/19-20)',
    ranged:'',
    space:'',
    reach:'',
    special_attacks:'trumpet',
    spell_like_abilities:'(CL 14th) - Constant—magic circle against evil; At will—aid, continual flame, detect evil, greater teleport (self plus 50 lbs. of objects only), message',
    spells_known:'',
    spells_prepared:'(CL 14th) - 7th—mass cure serious wounds (2); 6th—banishment (DC 21), heal (2); 5th—dispel evil (DC 20), mass cure light wounds, plane shift (DC 20), raise dead;
4th—dismissal (DC 19), divine power, neutralize poison (DC 19), spell immunity; 3rd—cure serious wounds, daylight, invisibility purge, magic vestment, protection from energy; 2nd—bull"s
strength, consecrate, cure moderate wounds (2), lesser restoration (2), owl"s wisdom; 1st—bless, cure light wounds (3), divine favor, sanctuary (DC 16), shield of faith; 0 (at will)—detect
magic, purify food and drink, stabilize, virtue',
    str:'20',
    dex:'17',
    con:'25',
    int:'16',
    wis:'20',
    cha:'17',
    base_atk:'+14',
    cmb:'+19',
    cmd:'32',
    feats:'Blind-Fight, Cleave, Combat Reflexes, Improved Initiative, Lightning Reflexes, Persuasive, Power Attack',
    skills:'Diplomacy +24, Escape Artist +17, Fly +24, Handle Animal +20, Knowledge (religion) +20, Perception +22, Perform (wind instruments) +20, Sense Motive +24, Stealth +20',
    racial_modifiers:'',
    languages:'Celestial, Draconic, Infernal; truespeech',
    sq:'',
    env:'any (Heaven)',
    organization:'solitary, pair, or squad (3–5)',
    treasure:'standard',
    special_abilities:'Trumpet (Su), Spells',
    more_info_link:'http://www.d20pfsrd.com/bestiary/monster-listings/outsiders/archon/trumpet-archon'
)
grindylow = Monster.create!(
    name:'Grindylow',
    cr:0.5,
    xp:200,
    description:'With a large head and numerous teeth, this unsightly creature resembles a goblin from the waist up and a greasy octopus below.',
    race_class_level:'',
    align_size_type:'CE Small aberration (aquatic)',
    init:'+2',
    senses:'darkvision 60 ft.; Perception +4',
    aura:'',
    ac:'15, touch 13, flat-footed 13 (+2 Dex, +2 natural, +1 size)',
    hp:'5 (1d8+1)',
    fort:'+1',
    ref:'+2',
    will:'+2',
    defensive_abilities:'',
    dr:'',
    immune:'',
    resist:'',
    sr:'',
    weaknesses:'',
    speed:'15 ft., swim 30 ft., jet 200 ft.',
    melee:'spear +2 (1d6+1/×3), bite –2 (1d3)',
    ranged:'spear +3 (1d6+1/×3)',
    space:'',
    reach:'',
    special_attacks:'tangling tentacles',
    spell_like_abilities:'',
    spells_known:'',
    spells_prepared:'',
    str:'12',
    dex:'14',
    con:'13',
    int:'9',
    wis:'10',
    cha:'9',
    base_atk:'+0',
    cmb:'+0 (+4 trip)',
    cmd:'12 (18 vs. trip)',
    feats:'Weapon Finesse',
    skills:'Perception +4, Stealth +14, Swim +13',
    racial_modifiers:'+4 Stealth, +8 Swim',
    languages:'Aquan',
    sq:'amphibious',
    env:'any water',
    organization:'solitary, pair, gang (3–9), warband (10–16 with 1–2 octopus minions), or tribe (17–40 plus 1 ranger sergeant of 1st–3rd level per 20 members, 1 cleric or barbarian leader of 4th-8th level, 2–8 octopus pets, and 1–2 devilfish guardians)',
    treasure:'NPC gear (spear, other treasure)',
    special_abilities:'Tangling Tentacles (Ex)',
    more_info_link:'http://www.d20pfsrd.com/bestiary/monster-listings/aberrations/grindylow'
)
aboleth = Monster.create!(
    name:'Aboleth',
    cr:7,
    xp:3200,
    description:'Four long tentacles writhe from this three-eyed fish-like creature"s flanks, and its green body glistens with thick, clear slime.',
    race_class_level:'',
    align_size_type:'LE Huge aberration (aquatic)',
    init:'+5',
    senses:'darkvision 60 ft.; Perception +14',
    aura:'mucus cloud (5 feet)',
    ac:'20, touch 9, flat-footed 19; (+1 Dex, +11 natural, –2 size)',
    hp:'84 (8d8+48)',
    fort:'+8',
    ref:'+5',
    will:'+11',
    defensive_abilities:'',
    dr:'',
    immune:'',
    resist:'',
    sr:'',
    weaknesses:'',
    speed:'10 ft., swim 60 ft.',
    melee:'4 tentacles +10 (1d6+5 plus slime)',
    ranged:'',
    space:'15 ft.',
    reach:'15 ft.',
    special_attacks:'',
    spell_like_abilities:'(CL 16th) At will—hypnotic pattern (DC 15), illusory wall (DC 17), mirage arcana (DC 18), persistent image (DC 18), programmed image (DC 19), project image (DC 20), veil (DC 19), 3/day—dominate monster (DC 22)',
    spells_known:'',
    spells_prepared:'',
    str:'20',
    dex:'12',
    con:'22',
    int:'15',
    wis:'17',
    cha:'17',
    base_atk:'+6',
    cmb:'+13',
    cmd:'24 (can"t be tripped)',
    feats:'Improved Initiative, Iron Will, Lightning Reflexes, Weapon Focus (tentacle)',
    skills:'Bluff +11, Intimidate +14, Knowledge (any one) +13, Perception +14, Spellcraft +13, Swim +24',
    racial_modifiers:'+8 Swim',
    languages:'Aboleth, Aklo, Aquan, Undercommon',
    sq:'',
    env:'any aquatic',
    organization:'solitary, pair, brood (3–6), or shoal (7–19)',
    treasure:'double',
    special_abilities:'Mucus Cloud (Ex), Slime (Ex)',
    more_info_link:'http://www.d20pfsrd.com/bestiary/monster-listings/aberrations/aboleth'
)
giant_fire_beetle = Monster.create!(
    name:'Giant Fire Beetle',
    cr:0.33,
    xp:135,
    description:'This housecat-sized beetle is a dull brown color brightened by two glowing green-yellow spots on its carapace.',
    race_class_level:'',
    align_size_type:'N Small vermin',
    init:'+0',
    senses:'low-light vision; Perception +0',
    aura:'',
    ac:'12, touch 11, flat-footed 12 (+1 natural, +1 size)',
    hp:'4 (1d8)',
    fort:'+2',
    ref:'+0',
    will:'+0',
    defensive_abilities:'',
    dr:'',
    immune:'mind-affecting effects',
    resist:'',
    sr:'',
    weaknesses:'',
    speed:'30 ft., fly 30 ft. (poor)',
    melee:'bite +1 (1d4)',
    ranged:'',
    space:'',
    reach:'',
    special_attacks:'',
    spell_like_abilities:'',
    spells_known:'',
    spells_prepared:'',
    str:'10',
    dex:'11',
    con:'11',
    int:'-',
    wis:'10',
    cha:'7',
    base_atk:'+0',
    cmb:'-1',
    cmd:'9 (17 vs. trip)',
    feats:'',
    skills:'Fly -2',
    racial_modifiers:'',
    languages:'',
    sq:'luminescence',
    env:'any',
    organization:'solitary, cluster (2–6) or colony (7–12)',
    treasure:'none',
    special_abilities:'Luminescence (Ex)',
    more_info_link:'http://www.d20pfsrd.com/bestiary/monster-listings/vermin/beetle/beetle-fire'
)
phoenix = Monster.create!(
    name:'Phoenix',
    cr:15,
    xp:51200,
    description:'This immense bird seems to be made of living flame. It spreads its wings and gives vent to a musical cry as it takes to the air.',
    race_class_level:'',
    align_size_type:'NG Gargantuan magical beast (fire)',
    init:'+11',
    senses:'darkvision 60 ft., detect magic, detect poison, low-light vision, see invisibility; Perception +37',
    aura:'shroud of flame (20 ft., 4d6 fire, DC 25)',
    ac:'28, touch 14, flat-footed 20 (+7 Dex, +1 dodge, +14 natural, –4 size)',
    hp:'210 (20d10+100); regeneration 10 (cold or evil)',
    fort:'+17',
    ref:'+19',
    will:'+14',
    defensive_abilities:'self-resurrection',
    dr:'15/evil',
    immune:'fire',
    resist:'',
    sr:'26',
    weaknesses:'vulnerable to cold',
    speed:'30 ft., fly 90 ft. (good)',
    melee:'2 talons +24 (2d6+8/19–20 plus 1d6 fire) and bite +24 (2d8+8 plus 1d6 fire) ',
    ranged:'',
    space:'20 ft.',
    reach:'20 ft.',
    special_attacks:'',
    spell_like_abilities:'(CL 18th) Constant—detect magic, detect poison, see invisibility; At will—continual flame, cure critical wounds, greater dispel magic, remove curse, wall of fire; 3/day—fire storm (DC 24), greater restoration, heal, mass cure critical wounds, quickened wall of fire',
    spells_known:'',
    spells_prepared:'',
    str:'27',
    dex:'25',
    con:'20',
    int:'23',
    wis:'22',
    cha:'22',
    base_atk:'+20',
    cmb:'+32',
    cmd:'50',
    feats:'Blinding Critical, Combat Reflexes, Critical Focus, Dodge, Flyby Attack, Improved Critical (talon), Improved Initiative, Iron Will, Mobility, Quicken Spell-Like Ability (wall of fire)',
    skills:'Acrobatics +30, Diplomacy +26, Fly +28, Intimidate +26, Knowledge (nature plus any one other) +26, Perception +37, Sense Motive +26',
    racial_modifiers:'+8 Perception',
    languages:'Auran, Celestial, Common, Ignan',
    sq:'',
    env:'warm desert and hills',
    organization:'solitary',
    treasure:'standard',
    special_abilities:'Self-Resurrection (Su), Shroud of Flame (Su), ',
    more_info_link:'http://www.d20pfsrd.com/bestiary/monster-listings/magical-beasts/phoenix'
)
chupacabra = Monster.create!(
    name:'Chupacabra',
    cr:3,
    xp:800,
    description:'This lizard-like creature stalks forward upon two muscular legs, a mane of spikes running down its scaly back.',
    race_class_level:'',
    align_size_type:'N Small magical beast ',
    init:'+7',
    senses:'darkvision 60 ft., low-light vision; Perception +6',
    aura:'',
    ac:'16, touch 14, flat-footed 13 (+3 Dex, +2 natural, +1 size)',
    hp:'30 (4d10+8)',
    fort:'+6',
    ref:'+7',
    will:'+3',
    defensive_abilities:'',
    dr:'',
    immune:'',
    resist:'',
    sr:'',
    weaknesses:'',
    speed:'30 ft.',
    melee:'bite +6 (1d4+1 plus grab), 2 claws +6 (1d3+1)',
    ranged:'',
    space:'',
    reach:'',
    special_attacks:'chupar, pounce',
    spell_like_abilities:'',
    spells_known:'',
    spells_prepared:'',
    str:'13',
    dex:'16',
    con:'14',
    int:'3',
    wis:'15',
    cha:'6',
    base_atk:'+4',
    cmb:'+4 (+8 grapple)',
    cmd:'17',
    feats:'Combat Reflexes, Improved Initiative',
    skills:'Acrobatics +7 (+11 jumping), Perception +6, Stealth +16',
    racial_modifiers:'+4 Acrobatics when jumping, +4 Stealth (+8 in undergrowth or rocky areas)',
    languages:'Aklo (cannot speak)',
    sq:'',
    env:'warm hills or plains',
    organization:'solitary, pair, or gang (3–7)',
    treasure:'none',
    special_abilities:'Chupar (Ex)',
    more_info_link:'http://www.d20pfsrd.com/bestiary/monster-listings/magical-beasts/chupacabra'
)
frumious_bandersnatch = Monster.create!(
    name:'Frumious Bandersnatch',
    cr:19,
    xp:204800,
    description:'This six-limbed beast stalks forward with a fluid grace. Barbed quills run along its back, and its eyes glow with a blue light.',
    race_class_level:'',
    align_size_type:'N Gargantuan magical beast',
    init:'+11',
    senses:'blindsense 120 ft., darkvision 120 ft., low-light vision, scent; Perception +26',
    aura:'',
    ac:'33, touch 13, flat-footed 26 (+7 Dex, +20 natural, -4 size)',
    hp:'310 (23d10+184); fast healing 10',
    fort:'+21',
    ref:'+20',
    will:'+11',
    defensive_abilities:'quick recovery, quill defense',
    dr:'',
    immune:'fear, paralysis, poison, sleep',
    resist:'fire 30',
    sr:'',
    weaknesses:'',
    speed:'60 ft., climb 20 ft.',
    melee:'bite +32 (2d8+13 plus grab), 2 claws +32 (2d6+13/19-20), tail slap +27 (2d8+19/x3 plus pain)',
    ranged:'4 quills +26 (1d10+13/19-20)',
    space:'20 ft.',
    reach:'15 ft. (20 ft. with tail slap)',
    special_attacks:'bounding charge, brutal tail, gaze, lash out, pounce, rake (4 claws, +32, 2d6+13/19-20), rend (2 claws, 2d6+19)',
    spell_like_abilities:'',
    spells_known:'',
    spells_prepared:'',
    str:'36',
    dex:'25',
    con:'27',
    int:'2',
    wis:'15',
    cha:'18',
    base_atk:'+23',
    cmb:'+40 (+44 grapple)',
    cmd:'57 (65 vs. trip)',
    feats:'Bleeding Critical, Combat Reflexes, Critical Focus, Critical Mastery, Exhausting Critical, Improved Critical (claws), Improved Critical (quills), Improved Initiative, Improved Iron Will, Iron Will, Skill Focus (Stealth), Tiring Critical',
    skills:'Acrobatics +19 (+31 when jumping), Climb +21, Perception +26, Stealth +18 (+26 forests), Survival +3 (+23 tracking)',
    racial_modifiers:'+8 Acrobatics, +10 Perception, +4 Stealth (+12 forests), +20 Survival when tracking',
    languages:'',
    sq:'fury, planar acclimation, relentless tracker',
    env:'any forests',
    organization:'solitary',
    treasure:'incidental',
    special_abilities:'Bounding Charge (Ex), Brutal Tail (Ex), Fury (Su), Gaze (Su), Lash Out (Ex), Pain (Ex), Planar Acclimation (Ex), Quill Defense (Ex), Quick Recovery (Su), Quills (Ex), Relentless Tracker (Ex)',
    more_info_link:'http://www.d20pfsrd.com/bestiary/monster-listings/magical-beasts/bandersnatch/bandersnatch-frumious'
)
# Add to the environment tables: Plane, Climate, Terrain
planes = Plane.create!([{name: 'Material Plane'}, {name: 'Outer/Elemental Plane'}])
climates = Climate.create!([{name: 'Cold'},{name: 'Temperate'}, {name: 'Warm'}, {name: 'Tropical'}, {name: 'Hot'}])
terrains = Terrain.create!([{name: 'Aquatic'}, {name: 'Deserts'}, {name: 'Forests'}, {name: 'Glaciers'},
                            {name: 'Hills'}, {name: 'Mountains'}, {name: 'Plains'}, {name: 'Ruins'},
                            {name: 'Swamps/Marshes'}, {name: 'Underground'}, {name: 'Urban'}])

# Add to the monster_plane table
owlbear.planes = [ Plane.find_by_name('Material Plane') ]
ghoul.planes = [ Plane.find_by_name('Material Plane') ]
ooze.planes = [ Plane.find_by_name('Material Plane') ]
shark.planes = [ Plane.find_by_name('Material Plane') ]
shoggoth.planes = [ Plane.find_by_name('Material Plane') ]
aasimar.planes = [ Plane.find_by_name('Material Plane') ]
archon.planes = [ Plane.find_by_name('Material Plane'), Plane.find_by_name('Outer/Elemental Plane') ]
grindylow.planes = [ Plane.find_by_name('Material Plane') ]
aboleth.planes = [ Plane.find_by_name('Material Plane') ]
giant_fire_beetle.planes = [ Plane.find_by_name('Material Plane'), Plane.find_by_name('Outer/Elemental Plane') ]
phoenix.planes = [ Plane.find_by_name('Material Plane') ]
chupacabra.planes = [ Plane.find_by_name('Material Plane') ]
frumious_bandersnatch.planes = [ Plane.find_by_name('Material Plane') ]

# Add to the monster_climate table
owlbear.climates = [ Climate.find_by_name('Temperate') ]
ghoul.climates = [ Climate.find_by_name('Cold'), Climate.find_by_name('Temperate'),
                   Climate.find_by_name('Warm'), Climate.find_by_name('Tropical'),
                   Climate.find_by_name('Hot') ]
ooze.climates = [ Climate.find_by_name('Cold'), Climate.find_by_name('Temperate'),
                  Climate.find_by_name('Warm'), Climate.find_by_name('Tropical'),
                  Climate.find_by_name('Hot') ]
shark.climates = [ Climate.find_by_name('Cold'), Climate.find_by_name('Temperate'),
                   Climate.find_by_name('Warm'), Climate.find_by_name('Tropical'),
                   Climate.find_by_name('Hot') ]
shoggoth.climates = [ Climate.find_by_name('Cold'), Climate.find_by_name('Temperate'),
                      Climate.find_by_name('Warm'), Climate.find_by_name('Tropical'),
                      Climate.find_by_name('Hot') ]
aasimar.climates = [ Climate.find_by_name('Cold'), Climate.find_by_name('Temperate'),
                     Climate.find_by_name('Warm'), Climate.find_by_name('Tropical'),
                     Climate.find_by_name('Hot') ]
archon.climates = [ Climate.find_by_name('Cold'), Climate.find_by_name('Temperate'),
                    Climate.find_by_name('Warm'), Climate.find_by_name('Tropical'),
                    Climate.find_by_name('Hot') ]
grindylow.climates = [ Climate.find_by_name('Cold'), Climate.find_by_name('Temperate'),
                       Climate.find_by_name('Warm'), Climate.find_by_name('Tropical'),
                       Climate.find_by_name('Hot') ]
aboleth.climates = [ Climate.find_by_name('Cold'), Climate.find_by_name('Temperate'),
                     Climate.find_by_name('Warm'), Climate.find_by_name('Tropical'),
                     Climate.find_by_name('Hot') ]
giant_fire_beetle.climates = [ Climate.find_by_name('Cold'), Climate.find_by_name('Temperate'),
                               Climate.find_by_name('Warm'), Climate.find_by_name('Tropical'),
                               Climate.find_by_name('Hot') ]
phoenix.climates = [ Climate.find_by_name('Warm') ]
chupacabra.climates = [ Climate.find_by_name('Warm') ]
frumious_bandersnatch.climates = [ Climate.find_by_name('Cold'), Climate.find_by_name('Temperate'),
                                   Climate.find_by_name('Warm'), Climate.find_by_name('Tropical'),
                                   Climate.find_by_name('Hot') ]

# Add to the monster_terrain table
owlbear.terrains = [ Terrain.find_by_name('Forests') ]
ghoul.terrains = [ Terrain.find_by_name('Deserts'), Terrain.find_by_name('Forests'),
                   Terrain.find_by_name('Glaciers'), Terrain.find_by_name('Hills'),
                   Terrain.find_by_name('Mountains'), Terrain.find_by_name('Plains'),
                   Terrain.find_by_name('Ruins'), Terrain.find_by_name('Swamps/Marshes'),
                   Terrain.find_by_name('Underground'), Terrain.find_by_name('Urban') ]
ooze.terrains = [ Terrain.find_by_name('Underground') ]
shark.terrains = [ Terrain.find_by_name('Aquatic') ]
shoggoth.terrains = [ Terrain.find_by_name('Aquatic'),Terrain.find_by_name('Underground') ]
aasimar.terrains = [ Terrain.find_by_name('Deserts'), Terrain.find_by_name('Forests'),
                     Terrain.find_by_name('Glaciers'), Terrain.find_by_name('Hills'),
                     Terrain.find_by_name('Mountains'), Terrain.find_by_name('Plains'),
                     Terrain.find_by_name('Ruins'), Terrain.find_by_name('Swamps/Marshes'),
                     Terrain.find_by_name('Underground'), Terrain.find_by_name('Urban') ]
archon.terrains = [ Terrain.find_by_name('Aquatic'), Terrain.find_by_name('Deserts'),
                    Terrain.find_by_name('Forests'), Terrain.find_by_name('Glaciers'),
                    Terrain.find_by_name('Hills'), Terrain.find_by_name('Mountains'),
                    Terrain.find_by_name('Plains'), Terrain.find_by_name('Ruins'),
                    Terrain.find_by_name('Swamps/Marshes'), Terrain.find_by_name('Underground'),
                    Terrain.find_by_name('Urban') ]
grindylow.terrains = [ Terrain.find_by_name('Aquatic') ]
aboleth.terrains = [ Terrain.find_by_name('Aquatic') ]
giant_fire_beetle.terrains = [ Terrain.find_by_name('Aquatic'), Terrain.find_by_name('Deserts'),
                      Terrain.find_by_name('Forests'), Terrain.find_by_name('Glaciers'),
                      Terrain.find_by_name('Hills'), Terrain.find_by_name('Mountains'),
                      Terrain.find_by_name('Plains'), Terrain.find_by_name('Ruins'),
                      Terrain.find_by_name('Swamps/Marshes'), Terrain.find_by_name('Underground'),
                      Terrain.find_by_name('Urban') ]
phoenix.terrains = [ Terrain.find_by_name('Deserts'), Terrain.find_by_name('Hills') ]
chupacabra.terrains = [ Terrain.find_by_name('Hills'), Terrain.find_by_name('Plains') ]
frumious_bandersnatch.terrains = [ Terrain.find_by_name('Forests') ]