# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Monster.delete_all
Plane.delete_all
Climate.delete_all
Terrain.delete_all
MonsterClimate.delete_all
MonsterPlane.delete_all
MonsterTerrain.delete_all


Monster.transaction do
  owlbear = Monster.create!(
      name:'Owlbear',
      cr:4,
      xp:1200,
      description:'An amalgam of fur and feathers, this bizarre half-bear, half-owl monstrosity raises its huge, ursine claws in anger.',
      race_class_level:'',
      align_size_type:'N Large magical beast',
      init:'+5',
      senses:'darkvision 60 ft., low-light vision, scent; Perception +12',
      aura:'',
      ac:'15, touch 10, flat-footed 14 (+1 Dex, +5 natural, –1 size)',
      hp:'47 (5d10+20)',
      fort:'+10',
      ref:'+5',
      will:'+2',
      defensive_abilities:'',
      dr:'',
      immune:'',
      resist:'',
      sr:'',
      weaknesses:'',
      speed:'30 ft.',
      melee:'2 claws +8 (1d6+4 plus grab), bite +8 (1d6+4)',
      ranged:'',
      space:'10 ft.',
      reach:'5 ft.',
      special_attacks:'',
      spell_like_abilities:'',
      spells_known:'',
      spells_prepared:'',
      str:'19',
      dex:'12',
      con:'18',
      int:'2',
      wis:'12',
      cha:'10',
      base_atk:'+5',
      cmb:'+10 (+14 grapple)',
      cmd:'21 (25 vs. trip)',
      feats:'Improved Initiative, Great Fortitude, Skill Focus (Perception)',
      skills:'Perception +12',
      racial_modifiers:'',
      languages:'',
      sq:'',
      env:'temperate forests',
      organization:'solitary, pair, or pack (3–8)',
      treasure:'incidental',
      special_abilities:'',
      more_info_link:'http://www.d20pfsrd.com/bestiary/monster-listings/magical-beasts/owlbear',
      max_num:8,
      gear:'',
      tactics:''
  )
  ghoul = Monster.create!(
      name:'Ghoul',
      cr:1,
      xp:400,
      description:'This humanoid creature has long, sharp teeth, and its pallid flesh is stretched tightly over its starved frame.',
      race_class_level:'',
      align_size_type:'CE Medium undead',
      init:'+2',
      senses:'darkvision 60 ft.; Perception +7',
      aura:'',
      ac:'14, touch 12, flat-footed 12 (+2 Dex, +2 natural)',
      hp:'13 (2d8+4)',
      fort:'+2',
      ref:'+2',
      will:'+5',
      defensive_abilities:'channel resistance +2; Immune undead traits',
      dr:'',
      immune:'',
      resist:'',
      sr:'',
      weaknesses:'',
      speed:'30 ft.',
      melee:'bite +3 (1d6+1 plus disease and paralysis) and 2 claws +3 (1d6+1 plus paralysis)',
      ranged:'',
      space:'',
      reach:'',
      special_attacks:'paralysis (1d4+1 rounds, DC 13, elves are immune to this effect)',
      spell_like_abilities:'',
      spells_known:'',
      spells_prepared:'',
      str:'13',
      dex:'15',
      con:'-',
      int:'13',
      wis:'14',
      cha:'14',
      base_atk:'+1',
      cmb:'+2',
      cmd:'14',
      feats:'Weapon Finesse',
      skills:'Acrobatics +4, Climb +6, Perception +7, Stealth +7, Swim +3',
      racial_modifiers:'',
      languages:'Common',
      sq:'',
      env:'any land',
      organization:'solitary, gang (2–4), or pack (7–12)',
      treasure:'standard',
      special_abilities:'Disease (Su): Ghoul Fever: Bite—injury; save Fort DC 13; onset 1 day; frequency 1/day; effect 1d3 Con and 1d3 Dex damage; cure 2 consecutive saves. The save DC is Charisma-based.',
      more_info_link:'http://www.d20pfsrd.com/bestiary/monster-listings/undead/ghoul',
      max_num:12,
      gear:'',
      tactics:''
  )
  ooze = Monster.create!(
      name:'Ooze (Cube, Gelatinous)',
      cr:3,
      xp:800,
      description:'Bits of broken weapons, coins, and a partially digested skeleton are visible inside this quivering cube of slime.',
      race_class_level:'',
      align_size_type:'N Large ooze',
      init:'-5',
      senses:'blindsight 60 ft.; Perception –5',
      aura:'',
      ac:'4, touch 4, flat-footed 4 (–5 Dex, –1 size)',
      hp:'50 (4d8+32)',
      fort:'+9',
      ref:'-4',
      will:'-4',
      defensive_abilities:'',
      dr:'',
      immune:'electricity, ooze traits',
      resist:'',
      sr:'',
      weaknesses:'',
      speed:'15 ft.',
      melee:'slam +2 (1d6 plus 1d6 acid)',
      ranged:'',
      space:'10 ft.',
      reach:'5 ft.',
      special_attacks:'engulf, paralysis',
      spell_like_abilities:'',
      spells_known:'',
      spells_prepared:'',
      str:'10',
      dex:'1',
      con:'26',
      int:'-',
      wis:'1',
      cha:'1',
      base_atk:'+3',
      cmb:'+4',
      cmd:'9 (cannot be tripped)',
      feats:'',
      skills:'',
      racial_modifiers:'',
      languages:'',
      sq:'transparent',
      env:'any underground',
      organization:'solitary',
      treasure:'incidental',
      special_abilities:'Acid (Ex), Engulf (Ex), Paralysis (Ex), Transparent (Ex)',
      more_info_link:'http://www.d20pfsrd.com/bestiary/monster-listings/oozes/gelatinous-cube',
      max_num:1,
      gear:'',
      tactics:''
  )
  shark = Monster.create!(
      name:'Common Shark',
      cr:2,
      xp:600,
      description:'This blue shark"s fins slice through the water, its black eyes rolling and its gaping jaws showing countless teeth.',
      race_class_level:'',
      align_size_type:'N Large animal (aquatic)',
      init:'+5',
      senses:'blindsense 30 ft., keen scent; Perception +8',
      aura:'',
      ac:'14, touch 10, flat-footed 13 (+1 Dex, +4 natural, –1 size)',
      hp:'22 (4d8+4)',
      fort:'+7',
      ref:'+5',
      will:'+2',
      defensive_abilities:'',
      dr:'',
      immune:'',
      resist:'',
      sr:'',
      weaknesses:'',
      speed:'swim 60 ft.',
      melee:'bite +5 (1d8+4)',
      ranged:'',
      space:'10 ft.',
      reach:'5 ft.',
      special_attacks:'',
      spell_like_abilities:'',
      spells_known:'',
      spells_prepared:'',
      str:'17',
      dex:'12',
      con:'13',
      int:'1',
      wis:'12',
      cha:'2',
      base_atk:'+3',
      cmb:'+7',
      cmd:'18',
      feats:'Great Fortitude, Improved Initiative',
      skills:'Perception +8, Swim +11',
      racial_modifiers:'',
      languages:'',
      sq:'',
      env:'any ocean',
      organization:'solitary, pair, school (3–6), or pack (7–13)',
      treasure:'none',
      special_abilities:'',
      more_info_link:'http://www.d20pfsrd.com/bestiary/monster-listings/animals/shark/shark',
      max_num:13,
      gear:'',
      tactics:''
  )
  shoggoth = Monster.create!(
      name:'Shoggoth',
      cr:19,
      xp:204800,
      description:'This immense mound of black slime thunders forward, eyes and mouths and even stranger things forming in its heaving bulk.',
      race_class_level:'',
      align_size_type:'CN Huge ooze (aquatic)',
      init:'+11',
      senses:'all-around vision, darkvision 120 ft., low-light vision, scent, tremorsense 60 ft.; Perception +33',
      aura:'',
      ac:'33, touch 15, flat-footed 26 (+7 Dex, +18 natural, –2 size)',
      hp:'333 (23d8+230); fast healing 10',
      fort:'+19',
      ref:'+14',
      will:'+15',
      defensive_abilities:'',
      dr:'10/—',
      immune:'blindness, charm effects, cold, deafness, ooze traits, sonic',
      resist:'acid 20, electricity 20, fire 20',
      sr:'30',
      weaknesses:'',
      speed:'50 ft., climb 30 ft., swim 50 ft.',
      melee:'4 slams +30 (3d6+15/19–20 plus grab) ',
      ranged:'',
      space:'15 ft.',
      reach:'30 ft.',
      special_attacks:'constrict (3d6+15), maddening cacophony, engulf (4d6+22 bludgeoning damage plus 8d6 acid damage, AC 19, hp 33), trample (4d8+15, DC 36)',
      spell_like_abilities:'',
      spells_known:'',
      spells_prepared:'',
      str:'40',
      dex:'24',
      con:'31',
      int:'5',
      wis:'22',
      cha:'13',
      base_atk:'+17',
      cmb:'+34 (+39 grapple)',
      cmd:'51 (cannot be tripped)',
      feats:'Blind-Fight, Cleave, Combat Reflexes, Critical Focus, Great Cleave, Great Fortitude, Improved Critical (slam), Improved Initiative, Improved Sunder, Iron Will, Power Attack, Staggering Critical',
      skills:'Climb +23, Perception +33, Swim +23',
      racial_modifiers:'+4 Perception',
      languages:'Aklo',
      sq:'amphibious',
      env:'cold aquatic or underground',
      organization:'solitary or tide (2–6)',
      treasure:'standard',
      special_abilities:'All-Around Vision (Ex), Maddening Cacophony (Su), Engulf (Ex)',
      more_info_link:'http://www.d20pfsrd.com/bestiary/monster-listings/oozes/shoggoth',
      max_num:6,
      gear:'',
      tactics:''
  )
  aasimar = Monster.create!(
      name:'Aasimar',
      cr:0.5,
      xp:200,
      description:'This supernaturally beautiful woman looks human, yet emanates a strange sense of calm and benevolence.',
      race_class_level:'Aasimar cleric 1',
      align_size_type:'NG Medium outsider (native)',
      init:'+0',
      senses:'darkvision 60 ft.; Perception +5',
      aura:'',
      ac:'15, touch 10, flat-footed 15 (+5 armor)',
      hp:'11 (1d8+3)',
      fort:'+4',
      ref:'+0',
      will:'+5',
      defensive_abilities:'',
      dr:'',
      immune:'',
      resist:'acid 5, cold 5, electricity 5',
      sr:'',
      weaknesses:'',
      speed:'30 ft. (20 ft. in armor)',
      melee:'heavy mace –1 (1d8–1)',
      ranged:'light crossbow +0 (1d8/19–20)',
      space:'',
      reach:'',
      special_attacks:'channel positive energy (5/day, 1d6, DC 12); rebuke death (1d4+1, 6/day); touch of good (6/day)',
      spell_like_abilities:'(CL 1st) - 1/day–daylight',
      spells_known:'',
      spells_prepared:'(CL 1st) - 1st–bless, command (DC 14), protection from evilD; 0th (at will)–detect magic, guidance, stabilize; D domain spell; Domains Good, Healing',
      str:'8',
      dex:'10',
      con:'14',
      int:'13',
      wis:'17',
      cha:'14',
      base_atk:'+0',
      cmb:'-1',
      cmd:'9',
      feats:'Turn Undead',
      skills:'Diplomacy +8, Heal +7, Knowledge (religion) +5',
      racial_modifiers:'+2 Diplomacy, +2 Perception',
      languages:'Celestial, Common, Draconic',
      sq:'',
      env:'any land',
      organization:'solitary, pair, or team (3–6)',
      treasure:'NPC gear (scale mail, heavy mace, light crossbow with 10 bolts, other treasure)',
      special_abilities:'',
      more_info_link:'http://www.d20pfsrd.com/bestiary/monster-listings/outsiders/aasimar',
      max_num:6,
      gear:'',
      tactics:''
  )
  archon = Monster.create!(
      name:'Trumpet Archon',
      cr:14,
      xp:38400,
      description:'Lithe and beautiful, with skin the color of marble, this being hovers upon powerful, white wings and radiates a sense of serenity.',
      race_class_level:'',
      align_size_type:'LG Medium outsider (archon, extraplanar, good, lawful)',
      init:'+7',
      senses:'darkvision 60 ft., low-light vision; Perception +22',
      aura:'aura of menace (DC 22), magic circle against evil',
      ac:'27, touch 13, flat-footed 24 (+3 Dex, +14 natural; +2 deflection vs. evil)',
      hp:'175 (14d10+98)',
      fort:'+16',
      ref:'+9',
      will:'+14; +4 vs. poison, +2 resistance vs. evil',
      defensive_abilities:'',
      dr:'10/evil',
      immune:'electricity, petrification',
      resist:'',
      sr:'25',
      weaknesses:'',
      speed:'40 ft., fly 90 ft. (good)',
      melee:'+4 greatsword +23/+18/+13 (2d6+11/19-20)',
      ranged:'',
      space:'',
      reach:'',
      special_attacks:'',
      spell_like_abilities:'(CL 14th) - Constant—magic circle against evil; At will—aid, continual flame, detect evil, greater teleport (self plus 50 lbs. of objects only), message',
      spells_known:'',
      spells_prepared:'(CL 14th) - 7th—mass cure serious wounds (2); 6th—banishment (DC 21), heal (2); 5th—dispel evil (DC 20), mass cure light wounds, plane shift (DC 20), raise dead;
4th—dismissal (DC 19), divine power, neutralize poison (DC 19), spell immunity; 3rd—cure serious wounds, daylight, invisibility purge, magic vestment, protection from energy; 2nd—bull"s
strength, consecrate, cure moderate wounds (2), lesser restoration (2), owl"s wisdom; 1st—bless, cure light wounds (3), divine favor, sanctuary (DC 16), shield of faith; 0 (at will)—detect
magic, purify food and drink, stabilize, virtue',
      str:'20',
      dex:'17',
      con:'25',
      int:'16',
      wis:'20',
      cha:'17',
      base_atk:'+14',
      cmb:'+19',
      cmd:'32',
      feats:'Blind-Fight, Cleave, Combat Reflexes, Improved Initiative, Lightning Reflexes, Persuasive, Power Attack',
      skills:'Diplomacy +24, Escape Artist +17, Fly +24, Handle Animal +20, Knowledge (religion) +20, Perception +22, Perform (wind instruments) +20, Sense Motive +24, Stealth +20',
      racial_modifiers:'',
      languages:'Celestial, Draconic, Infernal; truespeech',
      sq:'',
      env:'any (Heaven)',
      organization:'solitary, pair, or squad (3–5)',
      treasure:'standard',
      special_abilities:'Trumpet (Su), Spells',
      more_info_link:'http://www.d20pfsrd.com/bestiary/monster-listings/outsiders/archon/trumpet-archon',
      max_num:5,
      gear:'',
      tactics:''
  )
  grindylow = Monster.create!(
      name:'Grindylow',
      cr:0.5,
      xp:200,
      description:'With a large head and numerous teeth, this unsightly creature resembles a goblin from the waist up and a greasy octopus below.',
      race_class_level:'',
      align_size_type:'CE Small aberration (aquatic)',
      init:'+2',
      senses:'darkvision 60 ft.; Perception +4',
      aura:'',
      ac:'15, touch 13, flat-footed 13 (+2 Dex, +2 natural, +1 size)',
      hp:'5 (1d8+1)',
      fort:'+1',
      ref:'+2',
      will:'+2',
      defensive_abilities:'',
      dr:'',
      immune:'',
      resist:'',
      sr:'',
      weaknesses:'',
      speed:'15 ft., swim 30 ft., jet 200 ft.',
      melee:'spear +2 (1d6+1/×3), bite –2 (1d3)',
      ranged:'spear +3 (1d6+1/×3)',
      space:'',
      reach:'',
      special_attacks:'tangling tentacles',
      spell_like_abilities:'',
      spells_known:'',
      spells_prepared:'',
      str:'12',
      dex:'14',
      con:'13',
      int:'9',
      wis:'10',
      cha:'9',
      base_atk:'+0',
      cmb:'+0 (+4 trip)',
      cmd:'12 (18 vs. trip)',
      feats:'Weapon Finesse',
      skills:'Perception +4, Stealth +14, Swim +13',
      racial_modifiers:'+4 Stealth, +8 Swim',
      languages:'Aquan',
      sq:'amphibious',
      env:'any water',
      organization:'solitary, pair, gang (3–9), warband (10–16 with 1–2 octopus minions), or tribe (17–40 plus 1 ranger sergeant of 1st–3rd level per 20 members, 1 cleric or barbarian leader of 4th-8th level, 2–8 octopus pets, and 1–2 devilfish guardians)',
      treasure:'NPC gear (spear, other treasure)',
      special_abilities:'Tangling Tentacles (Ex)',
      more_info_link:'http://www.d20pfsrd.com/bestiary/monster-listings/aberrations/grindylow',
      max_num:40,
      gear:'',
      tactics:''
  )
  aboleth = Monster.create!(
      name:'Aboleth',
      cr:7,
      xp:3200,
      description:'Four long tentacles writhe from this three-eyed fish-like creature"s flanks, and its green body glistens with thick, clear slime.',
      race_class_level:'',
      align_size_type:'LE Huge aberration (aquatic)',
      init:'+5',
      senses:'darkvision 60 ft.; Perception +14',
      aura:'mucus cloud (5 feet)',
      ac:'20, touch 9, flat-footed 19; (+1 Dex, +11 natural, –2 size)',
      hp:'84 (8d8+48)',
      fort:'+8',
      ref:'+5',
      will:'+11',
      defensive_abilities:'',
      dr:'',
      immune:'',
      resist:'',
      sr:'',
      weaknesses:'',
      speed:'10 ft., swim 60 ft.',
      melee:'4 tentacles +10 (1d6+5 plus slime)',
      ranged:'',
      space:'15 ft.',
      reach:'15 ft.',
      special_attacks:'',
      spell_like_abilities:'(CL 16th) At will—hypnotic pattern (DC 15), illusory wall (DC 17), mirage arcana (DC 18), persistent image (DC 18), programmed image (DC 19), project image (DC 20), veil (DC 19), 3/day—dominate monster (DC 22)',
      spells_known:'',
      spells_prepared:'',
      str:'20',
      dex:'12',
      con:'22',
      int:'15',
      wis:'17',
      cha:'17',
      base_atk:'+6',
      cmb:'+13',
      cmd:'24 (can"t be tripped)',
      feats:'Improved Initiative, Iron Will, Lightning Reflexes, Weapon Focus (tentacle)',
      skills:'Bluff +11, Intimidate +14, Knowledge (any one) +13, Perception +14, Spellcraft +13, Swim +24',
      racial_modifiers:'+8 Swim',
      languages:'Aboleth, Aklo, Aquan, Undercommon',
      sq:'',
      env:'any aquatic',
      organization:'solitary, pair, brood (3–6), or shoal (7–19)',
      treasure:'double',
      special_abilities:'Mucus Cloud (Ex), Slime (Ex)',
      more_info_link:'http://www.d20pfsrd.com/bestiary/monster-listings/aberrations/aboleth',
      max_num:19,
      gear:'',
      tactics:''
  )
  giant_fire_beetle = Monster.create!(
      name:'Giant Fire Beetle',
      cr:0.33,
      xp:135,
      description:'This housecat-sized beetle is a dull brown color brightened by two glowing green-yellow spots on its carapace.',
      race_class_level:'',
      align_size_type:'N Small vermin',
      init:'+0',
      senses:'low-light vision; Perception +0',
      aura:'',
      ac:'12, touch 11, flat-footed 12 (+1 natural, +1 size)',
      hp:'4 (1d8)',
      fort:'+2',
      ref:'+0',
      will:'+0',
      defensive_abilities:'',
      dr:'',
      immune:'mind-affecting effects',
      resist:'',
      sr:'',
      weaknesses:'',
      speed:'30 ft., fly 30 ft. (poor)',
      melee:'bite +1 (1d4)',
      ranged:'',
      space:'',
      reach:'',
      special_attacks:'',
      spell_like_abilities:'',
      spells_known:'',
      spells_prepared:'',
      str:'10',
      dex:'11',
      con:'11',
      int:'-',
      wis:'10',
      cha:'7',
      base_atk:'+0',
      cmb:'-1',
      cmd:'9 (17 vs. trip)',
      feats:'',
      skills:'Fly -2',
      racial_modifiers:'',
      languages:'',
      sq:'luminescence',
      env:'any',
      organization:'solitary, cluster (2–6) or colony (7–12)',
      treasure:'none',
      special_abilities:'Luminescence (Ex)',
      more_info_link:'http://www.d20pfsrd.com/bestiary/monster-listings/vermin/beetle/beetle-fire',
      max_num:12,
      gear:'',
      tactics:''
  )
  phoenix = Monster.create!(
      name:'Phoenix',
      cr:15,
      xp:51200,
      description:'This immense bird seems to be made of living flame. It spreads its wings and gives vent to a musical cry as it takes to the air.',
      race_class_level:'',
      align_size_type:'NG Gargantuan magical beast (fire)',
      init:'+11',
      senses:'darkvision 60 ft., detect magic, detect poison, low-light vision, see invisibility; Perception +37',
      aura:'shroud of flame (20 ft., 4d6 fire, DC 25)',
      ac:'28, touch 14, flat-footed 20 (+7 Dex, +1 dodge, +14 natural, –4 size)',
      hp:'210 (20d10+100); regeneration 10 (cold or evil)',
      fort:'+17',
      ref:'+19',
      will:'+14',
      defensive_abilities:'self-resurrection',
      dr:'15/evil',
      immune:'fire',
      resist:'',
      sr:'26',
      weaknesses:'vulnerable to cold',
      speed:'30 ft., fly 90 ft. (good)',
      melee:'2 talons +24 (2d6+8/19–20 plus 1d6 fire) and bite +24 (2d8+8 plus 1d6 fire) ',
      ranged:'',
      space:'20 ft.',
      reach:'20 ft.',
      special_attacks:'',
      spell_like_abilities:'(CL 18th) Constant—detect magic, detect poison, see invisibility; At will—continual flame, cure critical wounds, greater dispel magic, remove curse, wall of fire; 3/day—fire storm (DC 24), greater restoration, heal, mass cure critical wounds, quickened wall of fire',
      spells_known:'',
      spells_prepared:'',
      str:'27',
      dex:'25',
      con:'20',
      int:'23',
      wis:'22',
      cha:'22',
      base_atk:'+20',
      cmb:'+32',
      cmd:'50',
      feats:'Blinding Critical, Combat Reflexes, Critical Focus, Dodge, Flyby Attack, Improved Critical (talon), Improved Initiative, Iron Will, Mobility, Quicken Spell-Like Ability (wall of fire)',
      skills:'Acrobatics +30, Diplomacy +26, Fly +28, Intimidate +26, Knowledge (nature plus any one other) +26, Perception +37, Sense Motive +26',
      racial_modifiers:'+8 Perception',
      languages:'Auran, Celestial, Common, Ignan',
      sq:'',
      env:'warm desert and hills',
      organization:'solitary',
      treasure:'standard',
      special_abilities:'Self-Resurrection (Su), Shroud of Flame (Su), ',
      more_info_link:'http://www.d20pfsrd.com/bestiary/monster-listings/magical-beasts/phoenix',
      max_num:1,
      gear:'',
      tactics:''
  )
  chupacabra = Monster.create!(
      name:'Chupacabra',
      cr:3,
      xp:800,
      description:'This lizard-like creature stalks forward upon two muscular legs, a mane of spikes running down its scaly back.',
      race_class_level:'',
      align_size_type:'N Small magical beast ',
      init:'+7',
      senses:'darkvision 60 ft., low-light vision; Perception +6',
      aura:'',
      ac:'16, touch 14, flat-footed 13 (+3 Dex, +2 natural, +1 size)',
      hp:'30 (4d10+8)',
      fort:'+6',
      ref:'+7',
      will:'+3',
      defensive_abilities:'',
      dr:'',
      immune:'',
      resist:'',
      sr:'',
      weaknesses:'',
      speed:'30 ft.',
      melee:'bite +6 (1d4+1 plus grab), 2 claws +6 (1d3+1)',
      ranged:'',
      space:'',
      reach:'',
      special_attacks:'chupar, pounce',
      spell_like_abilities:'',
      spells_known:'',
      spells_prepared:'',
      str:'13',
      dex:'16',
      con:'14',
      int:'3',
      wis:'15',
      cha:'6',
      base_atk:'+4',
      cmb:'+4 (+8 grapple)',
      cmd:'17',
      feats:'Combat Reflexes, Improved Initiative',
      skills:'Acrobatics +7 (+11 jumping), Perception +6, Stealth +16',
      racial_modifiers:'+4 Acrobatics when jumping, +4 Stealth (+8 in undergrowth or rocky areas)',
      languages:'Aklo (cannot speak)',
      sq:'',
      env:'warm hills or plains',
      organization:'solitary, pair, or gang (3–7)',
      treasure:'none',
      special_abilities:'Chupar (Ex)',
      more_info_link:'http://www.d20pfsrd.com/bestiary/monster-listings/magical-beasts/chupacabra',
      max_num:7,
      gear:'',
      tactics:''
  )
  frumious_bandersnatch = Monster.create!(
      name:'Frumious Bandersnatch',
      cr:19,
      xp:204800,
      description:'This six-limbed beast stalks forward with a fluid grace. Barbed quills run along its back, and its eyes glow with a blue light.',
      race_class_level:'',
      align_size_type:'N Gargantuan magical beast',
      init:'+11',
      senses:'blindsense 120 ft., darkvision 120 ft., low-light vision, scent; Perception +26',
      aura:'',
      ac:'33, touch 13, flat-footed 26 (+7 Dex, +20 natural, -4 size)',
      hp:'310 (23d10+184); fast healing 10',
      fort:'+21',
      ref:'+20',
      will:'+11',
      defensive_abilities:'quick recovery, quill defense',
      dr:'',
      immune:'fear, paralysis, poison, sleep',
      resist:'fire 30',
      sr:'',
      weaknesses:'',
      speed:'60 ft., climb 20 ft.',
      melee:'bite +32 (2d8+13 plus grab), 2 claws +32 (2d6+13/19-20), tail slap +27 (2d8+19/x3 plus pain)',
      ranged:'4 quills +26 (1d10+13/19-20)',
      space:'20 ft.',
      reach:'15 ft. (20 ft. with tail slap)',
      special_attacks:'bounding charge, brutal tail, gaze, lash out, pounce, rake (4 claws, +32, 2d6+13/19-20), rend (2 claws, 2d6+19)',
      spell_like_abilities:'',
      spells_known:'',
      spells_prepared:'',
      str:'36',
      dex:'25',
      con:'27',
      int:'2',
      wis:'15',
      cha:'18',
      base_atk:'+23',
      cmb:'+40 (+44 grapple)',
      cmd:'57 (65 vs. trip)',
      feats:'Bleeding Critical, Combat Reflexes, Critical Focus, Critical Mastery, Exhausting Critical, Improved Critical (claws), Improved Critical (quills), Improved Initiative, Improved Iron Will, Iron Will, Skill Focus (Stealth), Tiring Critical',
      skills:'Acrobatics +19 (+31 when jumping), Climb +21, Perception +26, Stealth +18 (+26 forests), Survival +3 (+23 tracking)',
      racial_modifiers:'+8 Acrobatics, +10 Perception, +4 Stealth (+12 forests), +20 Survival when tracking',
      languages:'',
      sq:'fury, planar acclimation, relentless tracker',
      env:'any forests',
      organization:'solitary',
      treasure:'incidental',
      special_abilities:'Bounding Charge (Ex), Brutal Tail (Ex), Fury (Su), Gaze (Su), Lash Out (Ex), Pain (Ex), Planar Acclimation (Ex), Quill Defense (Ex), Quick Recovery (Su), Quills (Ex), Relentless Tracker (Ex)',
      more_info_link:'http://www.d20pfsrd.com/bestiary/monster-listings/magical-beasts/bandersnatch/bandersnatch-frumious',
      max_num:1,
      gear:'',
      tactics:''
  )
  flumph = Monster.create!(
      name:'Flumph',
      cr:1,
      xp:400,
      description:'This pale, jellyfish-like creature floats gently in the air, two long eyestalks extending from either side of its puckered mouth.',
      race_class_level:'',
      align_size_type:'LG Small aberration',
      init:'+3',
      senses:'darkvision 60 ft.; Perception +7',
      aura:'',
      ac:'18, touch 14, flat-footed 15 (+3 Dex, +4 natural, +1 size)',
      hp:'9 (2d8)',
      fort:'+0',
      ref:'+3',
      will:'+5',
      defensive_abilities:'',
      dr:'',
      immune:'',
      resist:'',
      sr:'',
      weaknesses:'',
      speed:'5 ft., fly 20 ft. (perfect)',
      melee:'sting +5 (1d4 plus acid injection)',
      ranged:'',
      space:'',
      reach:'',
      special_attacks:'stench spray',
      spell_like_abilities:'',
      spells_known:'',
      spells_prepared:'',
      str:'10',
      dex:'16',
      con:'11',
      int:'10',
      wis:'14',
      cha:'10',
      base_atk:'+1',
      cmb:'+0',
      cmd:'13',
      feats:'Weapon Finesse',
      skills:'Diplomacy +2, Fly +18, Perception +7, Sense Motive +3, Stealth +11',
      racial_modifiers:'',
      languages:'Aklo, Common',
      sq:'',
      env:'any land or underground',
      organization:'solitary, pair, or colony (4-16)',
      treasure:'standard',
      special_abilities:'Acid Injection (Ex), Stench Spray (Ex)',
      more_info_link:'http://www.d20pfsrd.com/bestiary/monster-listings/aberrations/flumph',
      max_num:16,
      gear:'',
      tactics:''
  )
  lynx = Monster.create!(
      name:'Lynx (Cat, Great)',
      cr:2,
      xp:600,
      description:'This long-haired cat has tufts of black hair growing form the tips of its ears.',
      race_class_level:'',
      align_size_type:'N Small animal',
      init:'+2',
      senses:'low-light vision, scent; Perception +9',
      aura:'',
      ac:'14, touch 13, flat-footed 12 (+2 Dex, +1 natural, +1 size)',
      hp:'13 (2d8+4)',
      fort:'+5',
      ref:'+5',
      will:'+1',
      defensive_abilities:'',
      dr:'',
      immune:'',
      resist:'',
      sr:'',
      weaknesses:'',
      speed:'40 ft., climb 20 ft.',
      melee:'2 claw +4 (1d3+2 plus grab), bite +4 (1d4+2)',
      ranged:'',
      space:'',
      reach:'',
      special_attacks:'pounce, rake (2 claws +4, 1d3+2)',
      spell_like_abilities:'',
      spells_known:'',
      spells_prepared:'',
      str:'15',
      dex:'15',
      con:'15',
      int:'2',
      wis:'12',
      cha:'6',
      base_atk:'+1',
      cmb:'+2 (+6 grapple)',
      cmd:'14 (18 vs. trip)',
      feats:'Skill Focus (Perception)',
      skills:'Acrobatics +10, Climb +10, Perception +9, Stealth +10 (+14 in heavy undergrowth or tall grass)',
      racial_modifiers:'+8 Acrobatics, +4 Stealth (+8 in heavy undergrowth or tall grass)',
      languages:'',
      sq:'',
      env:'cold forests, hills, mountains and plains',
      organization:'solitary, pair or den (1–2 adults plus 1–6 cubs)',
      treasure:'none',
      special_abilities:'',
      more_info_link:'http://www.d20pfsrd.com/bestiary/monster-listings/animals/cat-great/lynx-tohc',
      max_num:8,
      gear:'',
      tactics:''
  )
  greenskin_orc = Monster.create!(
      name:'Greenskin Orc',
      cr:0.33,
      xp:135,
      description:'This creature looks like an ugly orc with green slime colored skin, small tusks, and canine-like eyes.',
      race_class_level:'Greenskin orc warrior 1',
      align_size_type:'CE Medium humanoid (orc)',
      init:'+2',
      senses:'darkvision 60 ft., scent; Perception +2',
      aura:'',
      ac:'14, touch 12, flat-footed 12 (+2 armor, +2 Dex)',
      hp:'7 (1d10+1 plus 1)',
      fort:'+3',
      ref:'+2',
      will:'-1',
      defensive_abilities:'ferocity',
      dr:'',
      immune:'',
      resist:'',
      sr:'',
      weaknesses:'light sensitivity',
      speed:'30 ft.',
      melee:'longsword +3 (1d8+2/19-20)',
      ranged:'composite longbow (+2 Str) +3 (1d8+2/x3)',
      space:'',
      reach:'',
      special_attacks:'',
      spell_like_abilities:'',
      spells_known:'',
      spells_prepared:'',
      str:'15',
      dex:'15',
      con:'12',
      int:'7',
      wis:'8',
      cha:'6',
      base_atk:'+1',
      cmb:'+3',
      cmd:'15',
      feats:'Point-Blank Shot',
      skills:'Perception +2, Stealth +2 (+6 in temperate and warm forests)',
      racial_modifiers:'+2 Perception, +4 Stealth in temperate and warm forests',
      languages:'Common, Orc',
      sq:'',
      env:'temperate and warm forests',
      organization:'gang (2-4), squad (11-20 plus 2 3rd-level sergeants and 1 leader of 3rd-6th level), band (30-300 plus 150% noncombatant plus 1 3rd-level sergeant per 10 adults, 5 5th-level lieutenants, and 3 7th-level captains)',
      treasure:'standard',
      special_abilities:'',
      more_info_link:'http://www.d20pfsrd.com/bestiary/monster-listings/humanoids/orcs/orc-greenskin',
      max_num:300,
      gear:'leather armor, longsword, composite longbow (+2 Str), 20 arrows, other treasure',
      tactics:''
  )
  goblin = Monster.create!(
      name:'Goblin',
      cr:0.33,
      xp:135,
      description:'This creature stands barely three feet tall, its scrawny, humanoid body dwarfed by its wide, ungainly head.',
      race_class_level:'Goblin warrior 1',
      align_size_type:'NE Small humanoid (goblinoid)',
      init:'+6',
      senses:'darkvision 60 ft.; Perception –1',
      aura:'',
      ac:'16, touch 13, flat-footed 14 (+2 armor, +2 Dex, +1 shield, +1 size)',
      hp:'6 (1d10+1)',
      fort:'+3',
      ref:'+2',
      will:'-1',
      defensive_abilities:'',
      dr:'',
      immune:'',
      resist:'',
      sr:'',
      weaknesses:'',
      speed:'30 ft.',
      melee:'short sword +2 (1d4/19–20)',
      ranged:'short bow +4 (1d4/×3)',
      space:'',
      reach:'',
      special_attacks:'',
      spell_like_abilities:'',
      spells_known:'',
      spells_prepared:'',
      str:'11',
      dex:'15',
      con:'12',
      int:'10',
      wis:'9',
      cha:'6',
      base_atk:'+1',
      cmb:'+0',
      cmd:'12',
      feats:'Improved Initiative',
      skills:'Ride +10, Stealth +10, Swim +4',
      racial_modifiers:'+4 Ride, +4 Stealth',
      languages:'Goblin',
      sq:'',
      env:'temperate forest and plains (usually coastal regions)',
      organization:'gang (4–9), warband (10–16 with goblin dog mounts), or tribe (17+ plus 100% noncombatants; 1 sergeant of 3rd level per 20 adults; 1 or 2 lieutenants of 4th or 5th level; 1 leader of 6th–8th level; and 10–40 goblin dogs, wolves, or worgs)',
      treasure:'NPC gear (leather armor, light wooden shield, short sword, short bow with 20 arrows, other treasure)',
      special_abilities:'',
      more_info_link:'http://www.d20pfsrd.com/bestiary/monster-listings/humanoids/goblin',
      max_num:40,
      gear:'',
      tactics:''
  )
  skeleton = Monster.create!(
      name:'Medium Skeleton',
      cr:0.33,
      xp:135,
      description:'The pile of bones suddenly stirs, rising up to take on a human shape. Its long, bony fingers reach out to claw at the living.',
      race_class_level:'',
      align_size_type:'NE Medium undead',
      init:'+6',
      senses:'darkvision 60 ft.; Perception +0',
      aura:'',
      ac:'16, touch 12, flat-footed 14 (+2 armor, +2 Dex, +2 natural)',
      hp:'4 (1d8)',
      fort:'+0',
      ref:'+2',
      will:'+2',
      defensive_abilities:'',
      dr:'5/bludgeoning',
      immune:'cold, undead traits',
      resist:'',
      sr:'',
      weaknesses:'',
      speed:'30 ft.',
      melee:'broken scimitar +0 (1d6), claw –3 (1d4+1) or 2 claws +2 (1d4+2)',
      ranged:'',
      space:'',
      reach:'',
      special_attacks:'',
      spell_like_abilities:'',
      spells_known:'',
      spells_prepared:'',
      str:'15',
      dex:'14',
      con:'-',
      int:'-',
      wis:'10',
      cha:'10',
      base_atk:'+0',
      cmb:'+2',
      cmd:'14',
      feats:'Improved Initiative',
      skills:'',
      racial_modifiers:'',
      languages:'',
      sq:'',
      env:'any',
      organization:'any',
      treasure:'none',
      special_abilities:'',
      more_info_link:'http://www.d20pfsrd.com/bestiary/monster-listings/undead/skeleton-medium',
      max_num:20,
      gear:'broken chain shirt, broken scimitar',
      tactics:''
  )
  mummy = Monster.create!(
      name:'Mummy',
      cr:5,
      xp:1600,
      description:'Wrapped from head to toe in ancient strips of moldering linen, this humanoid moves with a shuffling gait.',
      race_class_level:'',
      align_size_type:'LE Medium undead',
      init:'+0',
      senses:'darkvision 60 ft.; Perception +16',
      aura:'despair (30 ft., paralyzed for 1d4 rounds, Will DC 16 negates)',
      ac:'20, touch 10, flat-footed 20 (+10 natural)',
      hp:'60 (8d8+24)',
      fort:'+4',
      ref:'+2',
      will:'+8',
      defensive_abilities:'',
      dr:'5/-',
      immune:'undead traits',
      resist:'',
      sr:'',
      weaknesses:'vulnerable to fire',
      speed:'20 ft.',
      melee:'slam +14 (1d8+10 plus mummy rot)',
      ranged:'',
      space:'',
      reach:'',
      special_attacks:'',
      spell_like_abilities:'',
      spells_known:'',
      spells_prepared:'',
      str:'24',
      dex:'10',
      con:'-',
      int:'6',
      wis:'15',
      cha:'15',
      base_atk:'+6',
      cmb:'+13',
      cmd:'23',
      feats:'Power Attack, Toughness, Skill Focus (Perception), Weapon Focus',
      skills:'Perception +16, Stealth +11',
      racial_modifiers:'',
      languages:'Common',
      sq:'',
      env:'any',
      organization:'solitary, warden squad (2–6), or guardian detail (7–12)',
      treasure:'standard',
      special_abilities:'Despair (Su), Mummy Rot (Su), ',
      more_info_link:'http://www.d20pfsrd.com/bestiary/monster-listings/undead/mummy',
      max_num:12,
      gear:'',
      tactics:''
  )
  zombie = Monster.create!(
      name:'Zombie',
      cr:0.5,
      xp:200,
      description:'This walking corpse wears only a few soiled rags, its flesh rotting off its bones as it stumbles forward, arms outstretched.',
      race_class_level:'',
      align_size_type:'NE Medium undead',
      init:'+0',
      senses:'darkvision 60 ft.; Perception +0',
      aura:'',
      ac:'12, touch 10, flat-footed 12 (+2 natural)',
      hp:'12 (2d8+3)',
      fort:'+0',
      ref:'+0',
      will:'+3',
      defensive_abilities:'',
      dr:'5/slashing',
      immune:'undead traits',
      resist:'',
      sr:'',
      weaknesses:'',
      speed:'30 ft.',
      melee:'slam +4 (1d6+4)',
      ranged:'',
      space:'',
      reach:'',
      special_attacks:'staggered',
      spell_like_abilities:'',
      spells_known:'',
      spells_prepared:'',
      str:'17',
      dex:'10',
      con:'-',
      int:'-',
      wis:'10',
      cha:'10',
      base_atk:'+1',
      cmb:'+4',
      cmd:'14',
      feats:'Toughness',
      skills:'',
      racial_modifiers:'',
      languages:'',
      sq:'',
      env:'any',
      organization:'any',
      treasure:'none',
      special_abilities:'Staggered (Ex)',
      more_info_link:'http://www.d20pfsrd.com/bestiary/monster-listings/undead/zombie',
      max_num:50,
      gear:'',
      tactics:''
  )
  orcish_warclops = Monster.create!(
      name:'Orcish Warclops',
      cr:6,
      xp:2400,
      description:'Made from the severed limbs and ruined bodies of dozens of creatures, this crude construct is stitched together with cord and held together with chain. It stumbles about in a fury on three legs, flailing about with three mangled arms. Its grotesque head bellows in unintelligible rage as it gazes about with a single, over-sized eye.',
      race_class_level:'',
      align_size_type:'N Large construct',
      init:'-2',
      senses:'darkvision 60 ft., low-light vision; Perception +0',
      aura:'',
      ac:'19, touch 7, flat-footed 19 (+4 armor, –2 Dex, +8 natural, –1 size)',
      hp:'74 (8d10+30)',
      fort:'+2',
      ref:'+0',
      will:'+2',
      defensive_abilities:'',
      dr:'5/adamantine',
      immune:'construct traits, magic',
      resist:'',
      sr:'',
      weaknesses:'poorly made',
      speed:'40 ft.',
      melee:'3 slam +11 (2d6+4)',
      ranged:'',
      space:'10 ft.',
      reach:'10 ft.',
      special_attacks:'destructive frenzy',
      spell_like_abilities:'',
      spells_known:'',
      spells_prepared:'',
      str:'18',
      dex:'7',
      con:'-',
      int:'-',
      wis:'11',
      cha:'1',
      base_atk:'+8',
      cmb:'+13',
      cmd:'21 (23 vs. trip)',
      feats:'',
      skills:'',
      racial_modifiers:'',
      languages:'none',
      sq:'',
      env:'temperate hills, mountains, or underground',
      organization:'solitary or gang (2-4)',
      treasure:'none',
      special_abilities:'Destructive Frenzy (Ex), Immunity to Magic (Ex), Poorly Made (Ex)',
      more_info_link:'http://www.d20pfsrd.com/bestiary/monster-listings/constructs/orcish-warclops',
      max_num:4,
      gear:'',
      tactics:''
  )
  lion = Monster.create!(
      name:'Lion (Cat, Great)',
      cr:3,
      xp:800,
      description:'This great cat"s muscles flex visibly under its skin as it bares its fangs and shakes its thick mane of hair.',
      race_class_level:'',
      align_size_type:'N Large Animal',
      init:'+7',
      senses:'low-light vision, scent; Perception +9',
      aura:'',
      ac:'15, touch 12, flat-footed 12 (+3 Dex, +3 natural, –1 size)',
      hp:'32 (5d8+10)',
      fort:'+6',
      ref:'+7',
      will:'+2',
      defensive_abilities:'',
      dr:'',
      immune:'',
      resist:'',
      sr:'',
      weaknesses:'',
      speed:'40 ft.',
      melee:'bite +7 (1d8+5 plus grab), 2 claws +7 (1d4+5)',
      ranged:'',
      space:'10 ft.',
      reach:'5 ft.',
      special_attacks:'pounce, rake (2 claws +7, 1d4+5)',
      spell_like_abilities:'',
      spells_known:'',
      spells_prepared:'',
      str:'21',
      dex:'17',
      con:'15',
      int:'2',
      wis:'12',
      cha:'6',
      base_atk:'+3',
      cmb:'+9 (+13 grapple)',
      cmd:'22 (26 vs. trip)',
      feats:'Improved Initiative, Run, Skill Focus (Perception)',
      skills:'Acrobatics +11, Perception +9, Stealth +8 (+12 in undergrowth)',
      racial_modifiers:'+4 Acrobatics, +4 Stealth (+8 in undergrowth)',
      languages:'',
      sq:'',
      env:'warm plains',
      organization:'solitary, pair, or pride (3–10)',
      treasure:'none',
      special_abilities:'',
      more_info_link:'http://www.d20pfsrd.com/bestiary/monster-listings/animals/cat-great/lion',
      max_num:10,
      gear:'',
      tactics:''
  )
  leopard = Monster.create!(
      name:'Leopard (Cat, Great)',
      cr:2,
      xp:600,
      description:'With each graceful step, this leopard"s steely muscles ripple beneath its spotted fur.',
      race_class_level:'',
      align_size_type:'N Medium animal',
      init:'+4',
      senses:'low-light vision, scent; Perception +5',
      aura:'',
      ac:'15, touch 14, flat-footed 11 (+4 Dex, +1 natural)',
      hp:'19 (3d8+6)',
      fort:'+5',
      ref:'+7',
      will:'+2',
      defensive_abilities:'',
      dr:'',
      immune:'',
      resist:'',
      sr:'',
      weaknesses:'',
      speed:'30 ft., climb 20 ft.',
      melee:'bite +6 (1d6+3 plus grab), 2 claws +6 (1d3+3)',
      ranged:'',
      space:'',
      reach:'',
      special_attacks:'pounce, rake (2 claws +6, 1d3+3)',
      spell_like_abilities:'',
      spells_known:'',
      spells_prepared:'',
      str:'16',
      dex:'19',
      con:'15',
      int:'2',
      wis:'13',
      cha:'6',
      base_atk:'+2',
      cmb:'+5 (+9 grapple)',
      cmd:'19 (23 vs. trip)',
      feats:'Skill Focus (Stealth), Weapon Finesse',
      skills:'Acrobatics +8, Climb +11, Perception +5, Stealth +11 (+15 in undergrowth)',
      racial_modifiers:'+4 on Stealth in undergrowth',
      languages:'',
      sq:'',
      env:'any forest',
      organization:'solitary or pair',
      treasure:'none',
      special_abilities:'',
      more_info_link:'http://www.d20pfsrd.com/bestiary/monster-listings/animals/cat-great/leopard',
      max_num:2,
      gear:'',
      tactics:''
  )
  robot_golem = Monster.create!(
      name:'Robot Golem',
      cr:11,
      xp:12800,
      description:'Though corroded and damaged, this bipedal metallic construct moves silently, as though powered by some force other than its own rattling gears.',
      race_class_level:'',
      align_size_type:'N Large construct',
      init:'+0',
      senses:'darkvision 60 ft., low-light vision; Perception +0',
      aura:'',
      ac:'27, touch 9, flat-footed 27 (+18 natural, –1 size)',
      hp:'112 (15d10+30)',
      fort:'+5',
      ref:'+5',
      will:'+5',
      defensive_abilities:'',
      dr:'10/adamantine',
      immune:'construct traits, magic',
      resist:'',
      sr:'',
      weaknesses:'',
      speed:'20 ft.',
      melee:'2 slams +22 (2d10+8)',
      ranged:'',
      space:'10 ft.',
      reach:'10 ft.',
      special_attacks:'rend construct (2 slams, 2d10+12), shockwave (30-ft.-radius spread, 8d6 electricity, Reflex DC 19 for half, usable every 1d4 rounds)',
      spell_like_abilities:'',
      spells_known:'',
      spells_prepared:'',
      str:'26',
      dex:'11',
      con:'-',
      int:'-',
      wis:'11',
      cha:'1',
      base_atk:'+15',
      cmb:'+24',
      cmd:'34',
      feats:'',
      skills:'',
      racial_modifiers:'',
      languages:'',
      sq:'',
      env:'any',
      organization:'solitary or gang (2–4)',
      treasure:'none',
      special_abilities:'Immunity to Magic (Ex), Rend Construct (Ex), Shockwave (Ex)',
      more_info_link:'http://www.d20pfsrd.com/bestiary/monster-listings/constructs/golem/golem-robot',
      max_num:4,
      gear:'',
      tactics:''
  )
  barbtongued_wyvern = Monster.create!(
      name:'Barbtongued Wyvern',
      cr:15,
      xp:51200,
      description:'Lithe and quick, these wyverns have long, barbed tongues capable of lashing out and pulling prey into their jaws. Their attitude is one of aggression if they sense intruders—they attack on sight.',
      race_class_level:'Advanced variant wyvern',
      align_size_type:'NE Huge dragon',
      init:'+2',
      senses:'darkvision 60 ft., low-light vision, scent; Perception +28',
      aura:'',
      ac:'27, touch 11, flat-footed 24 (+2 Dex, +1 dodge, +16 natural, –2 size)',
      hp:'250 (20d12+120)',
      fort:'+18',
      ref:'+14',
      will:'+13',
      defensive_abilities:'',
      dr:'',
      immune:'paralysis, sleep',
      resist:'',
      sr:'',
      weaknesses:'',
      speed:'20 ft., fly 60 ft. (poor)',
      melee:'sting +26 (2d6+8 plus poison), bite +26 (4d6+8/19–20), 2 wings +21 (2d6+4), tongue +21 (1d4+4 plus grab)',
      ranged:'',
      space:'15 ft.',
      reach:'15 ft.; 30 ft. with tongue',
      special_attacks:'pull (tongue, 30 ft.), rake (2 talons +26, 1d8+8)',
      spell_like_abilities:'',
      spells_known:'',
      spells_prepared:'',
      str:'27',
      dex:'14',
      con:'22',
      int:'7',
      wis:'12',
      cha:'9',
      base_atk:'+20',
      cmb:'+30',
      cmd:'43',
      feats:'Critical Focus, Dodge, Improved Critical (bite), Improved Natural Attack (bite), Improved Vital Strike, Improved Natural Attack (sting), Improved Natural Attack (wing), Power Attack, Staggering Critical, Vital Strike',
      skills:'Fly +17, Perception +28, Sense Motive +24, Stealth +17',
      racial_modifiers:'',
      languages:'Draconic',
      sq:'',
      env:'temperate or warm hills',
      organization:'solitary, pair, or flight (3–6)',
      treasure:'standard',
      special_abilities:'Poison (Ex)',
      more_info_link:'http://www.d20pfsrd.com/bestiary/monster-listings/dragons/wyvern/wyvern-barbtongued',
      max_num:6,
      gear:'',
      tactics:'If they can, the barbtongued wyverns start combat by swooping in to attack the PCs before the party can fully enter a room, limiting melee combat options while still being able to take advantage of their reach to strike at foes farther up the stairs or down a hall. Barbtongued wyverns fight to the death.'
  )
  mandragora = Monster.create!(
      name:'Immense Mandragora',
      cr:15,
      xp:51200,
      description:'Thousands of tiny mandragoras swarm up into a mound, quickly building their mass up and spreading their malleable bodies apart and together to form a single 35-foot-tall mandragora; an impressive trick they do quickly as soon as any threat is presented.',
      race_class_level:'',
      align_size_type:'CE Gargantuan plant',
      init:'+7',
      senses:'low-light vision; Perception +12',
      aura:'',
      ac:'18, touch 9, flat-footed 15 (+3 Dex, +9 natural, –4 size)',
      hp:'232 (16d8+160); fast healing 10',
      fort:'+20',
      ref:'+10',
      will:'+6',
      defensive_abilities:'',
      dr:'',
      immune:'plant traits',
      resist:'acid 5, cold 5, electricity 10',
      sr:'',
      weaknesses:'vulnerable to darkness',
      speed:'40 ft., burrow 10 ft., climb 40 ft.',
      melee:'2 vine whips +25 (2d8+17/19–20 plus poison), bite +25 (2d8+17)',
      ranged:'',
      space:'20 ft.',
      reach:'20 ft. (30 ft. with vine whips)',
      special_attacks:'shriek',
      spell_like_abilities:'',
      spells_known:'',
      spells_prepared:'',
      str:'45',
      dex:'17',
      con:'30',
      int:'8',
      wis:'13',
      cha:'10',
      base_atk:'+12',
      cmb:'+33',
      cmd:'46',
      feats:'Awesome Blow, Improved Bull Rush, Improved Critical (vine whips), Improved Initiative, Improved Vital Strike, Lightning Reflexes, Power Attack, Vital Strike',
      skills:'Climb +25, Fly +0, Perception +12, Stealth +0 (+8 in heavy plant growth)',
      racial_modifiers:'',
      languages:'Aklo, Common',
      sq:'',
      env:'First World',
      organization:'solitary or pair',
      treasure:'incidental',
      special_abilities:'Poison (Ex), Shriek (Su), Vulnerable to Darkness (Ex)',
      more_info_link:'http://www.d20pfsrd.com/bestiary/monster-listings/plants/mandragora/immense-mandragora',
      max_num:2,
      gear:'',
      tactics:'The mandragoras require the entire first round of combat to collect into their Gargantuan form. During this round, the immense mandragora cannot make attacks. Once it is fully formed, it uses Power Attack with every strike, and Awesome Blow against characters that are able to make large numbers of melee attacks trying to force the characters to take move actions to get back in range, thus minimizing the damage they do. The immense mandragora fights to the death.'
  )

# Add to the environment tables: Plane, Climate, Terrain
  planes = Plane.create!([{name: 'Material Plane'}, {name: 'Outer/Elemental Plane'}])
  climates = Climate.create!([{name: 'Cold'},{name: 'Temperate'}, {name: 'Warm'}, {name: 'Tropical'}, {name: 'Hot'}])
  terrains = Terrain.create!([{name: 'Aquatic'}, {name: 'Deserts'}, {name: 'Forests'}, {name: 'Glaciers'},
                              {name: 'Hills'}, {name: 'Mountains'}, {name: 'Plains'}, {name: 'Ruins'},
                              {name: 'Swamps/Marshes'}, {name: 'Underground'}, {name: 'Urban'}])

# Add to the monster_plane table
  owlbear.planes = [ Plane.find_by_name('Material Plane') ]
  ghoul.planes = [ Plane.find_by_name('Material Plane') ]
  ooze.planes = [ Plane.find_by_name('Material Plane') ]
  shark.planes = [ Plane.find_by_name('Material Plane') ]
  shoggoth.planes = [ Plane.find_by_name('Material Plane') ]
  aasimar.planes = [ Plane.find_by_name('Material Plane') ]
  archon.planes = [ Plane.find_by_name('Material Plane'), Plane.find_by_name('Outer/Elemental Plane') ]
  grindylow.planes = [ Plane.find_by_name('Material Plane') ]
  aboleth.planes = [ Plane.find_by_name('Material Plane') ]
  giant_fire_beetle.planes = [ Plane.find_by_name('Material Plane'), Plane.find_by_name('Outer/Elemental Plane') ]
  phoenix.planes = [ Plane.find_by_name('Material Plane') ]
  chupacabra.planes = [ Plane.find_by_name('Material Plane') ]
  frumious_bandersnatch.planes = [ Plane.find_by_name('Material Plane') ]
  flumph.planes = [ Plane.find_by_name('Material Plane') ]
  lynx.planes = [ Plane.find_by_name('Material Plane') ]
  greenskin_orc.planes = [ Plane.find_by_name('Material Plane') ]
  goblin.planes = [ Plane.find_by_name('Material Plane') ]
  skeleton.planes = [ Plane.find_by_name('Material Plane'), Plane.find_by_name('Outer/Elemental Plane') ]
  mummy.planes = [ Plane.find_by_name('Material Plane'), Plane.find_by_name('Outer/Elemental Plane') ]
  zombie.planes = [ Plane.find_by_name('Material Plane'), Plane.find_by_name('Outer/Elemental Plane') ]
  orcish_warclops.planes = [ Plane.find_by_name('Material Plane') ]
  lion.planes = [ Plane.find_by_name('Material Plane') ]
  leopard.planes = [ Plane.find_by_name('Material Plane') ]
  robot_golem.planes = [ Plane.find_by_name('Material Plane'), Plane.find_by_name('Outer/Elemental Plane') ]
  barbtongued_wyvern.planes = [ Plane.find_by_name('Material Plane') ]
  mandragora.planes = [ Plane.find_by_name('Material Plane') ]

# Add to the monster_climate table
  owlbear.climates = [ Climate.find_by_name('Temperate') ]
  ghoul.climates = [ Climate.find_by_name('Cold'), Climate.find_by_name('Temperate'),
                     Climate.find_by_name('Warm'), Climate.find_by_name('Tropical'),
                     Climate.find_by_name('Hot') ]
  ooze.climates = [ Climate.find_by_name('Cold'), Climate.find_by_name('Temperate'),
                    Climate.find_by_name('Warm'), Climate.find_by_name('Tropical'),
                    Climate.find_by_name('Hot') ]
  shark.climates = [ Climate.find_by_name('Cold'), Climate.find_by_name('Temperate'),
                     Climate.find_by_name('Warm'), Climate.find_by_name('Tropical'),
                     Climate.find_by_name('Hot') ]
  shoggoth.climates = [ Climate.find_by_name('Cold'), Climate.find_by_name('Temperate'),
                        Climate.find_by_name('Warm'), Climate.find_by_name('Tropical'),
                        Climate.find_by_name('Hot') ]
  aasimar.climates = [ Climate.find_by_name('Cold'), Climate.find_by_name('Temperate'),
                       Climate.find_by_name('Warm'), Climate.find_by_name('Tropical'),
                       Climate.find_by_name('Hot') ]
  archon.climates = [ Climate.find_by_name('Cold'), Climate.find_by_name('Temperate'),
                      Climate.find_by_name('Warm'), Climate.find_by_name('Tropical'),
                      Climate.find_by_name('Hot') ]
  grindylow.climates = [ Climate.find_by_name('Cold'), Climate.find_by_name('Temperate'),
                         Climate.find_by_name('Warm'), Climate.find_by_name('Tropical'),
                         Climate.find_by_name('Hot') ]
  aboleth.climates = [ Climate.find_by_name('Cold'), Climate.find_by_name('Temperate'),
                       Climate.find_by_name('Warm'), Climate.find_by_name('Tropical'),
                       Climate.find_by_name('Hot') ]
  giant_fire_beetle.climates = [ Climate.find_by_name('Cold'), Climate.find_by_name('Temperate'),
                                 Climate.find_by_name('Warm'), Climate.find_by_name('Tropical'),
                                 Climate.find_by_name('Hot') ]
  phoenix.climates = [ Climate.find_by_name('Warm') ]
  chupacabra.climates = [ Climate.find_by_name('Warm') ]
  frumious_bandersnatch.climates = [ Climate.find_by_name('Cold'), Climate.find_by_name('Temperate'),
                                     Climate.find_by_name('Warm'), Climate.find_by_name('Tropical'),
                                     Climate.find_by_name('Hot') ]
  flumph.climates = [ Climate.find_by_name('Cold'), Climate.find_by_name('Temperate'),
                      Climate.find_by_name('Warm'), Climate.find_by_name('Tropical'),
                      Climate.find_by_name('Hot') ]
  lynx.climates = [ Climate.find_by_name('Cold') ]
  greenskin_orc.climates = [ Climate.find_by_name('Temperate'), Climate.find_by_name('Warm') ]
  goblin.climates = [ Climate.find_by_name('Temperate') ]
  skeleton.climates = [ Climate.find_by_name('Cold'), Climate.find_by_name('Temperate'),
                        Climate.find_by_name('Warm'), Climate.find_by_name('Tropical'),
                        Climate.find_by_name('Hot') ]
  mummy.climates = [ Climate.find_by_name('Cold'), Climate.find_by_name('Temperate'),
                     Climate.find_by_name('Warm'), Climate.find_by_name('Tropical'),
                     Climate.find_by_name('Hot') ]
  zombie.climates = [ Climate.find_by_name('Cold'), Climate.find_by_name('Temperate'),
                      Climate.find_by_name('Warm'), Climate.find_by_name('Tropical'),
                      Climate.find_by_name('Hot') ]
  orcish_warclops.climates = [ Climate.find_by_name('Temperate') ]
  lion.climates = [ Climate.find_by_name('Warm') ]
  leopard.climates = [ Climate.find_by_name('Cold'), Climate.find_by_name('Temperate'),
                       Climate.find_by_name('Warm'), Climate.find_by_name('Tropical'),
                       Climate.find_by_name('Hot') ]
  robot_golem.climates = [ Climate.find_by_name('Cold'), Climate.find_by_name('Temperate'),
                           Climate.find_by_name('Warm'), Climate.find_by_name('Tropical'),
                           Climate.find_by_name('Hot') ]
  barbtongued_wyvern.climates = [ Climate.find_by_name('Temperate'), Climate.find_by_name('Warm') ]
  mandragora.climates = [ Climate.find_by_name('Cold'), Climate.find_by_name('Temperate'),
                          Climate.find_by_name('Warm'), Climate.find_by_name('Tropical'),
                          Climate.find_by_name('Hot') ]

# Add to the monster_terrain table
  owlbear.terrains = [ Terrain.find_by_name('Forests') ]
  ghoul.terrains = [ Terrain.find_by_name('Deserts'), Terrain.find_by_name('Forests'),
                     Terrain.find_by_name('Glaciers'), Terrain.find_by_name('Hills'),
                     Terrain.find_by_name('Mountains'), Terrain.find_by_name('Plains'),
                     Terrain.find_by_name('Ruins'), Terrain.find_by_name('Swamps/Marshes'),
                     Terrain.find_by_name('Underground'), Terrain.find_by_name('Urban') ]
  ooze.terrains = [ Terrain.find_by_name('Underground') ]
  shark.terrains = [ Terrain.find_by_name('Aquatic') ]
  shoggoth.terrains = [ Terrain.find_by_name('Aquatic'),Terrain.find_by_name('Underground') ]
  aasimar.terrains = [ Terrain.find_by_name('Deserts'), Terrain.find_by_name('Forests'),
                       Terrain.find_by_name('Glaciers'), Terrain.find_by_name('Hills'),
                       Terrain.find_by_name('Mountains'), Terrain.find_by_name('Plains'),
                       Terrain.find_by_name('Ruins'), Terrain.find_by_name('Swamps/Marshes'),
                       Terrain.find_by_name('Underground'), Terrain.find_by_name('Urban') ]
  archon.terrains = [ Terrain.find_by_name('Aquatic'), Terrain.find_by_name('Deserts'),
                      Terrain.find_by_name('Forests'), Terrain.find_by_name('Glaciers'),
                      Terrain.find_by_name('Hills'), Terrain.find_by_name('Mountains'),
                      Terrain.find_by_name('Plains'), Terrain.find_by_name('Ruins'),
                      Terrain.find_by_name('Swamps/Marshes'), Terrain.find_by_name('Underground'),
                      Terrain.find_by_name('Urban') ]
  grindylow.terrains = [ Terrain.find_by_name('Aquatic') ]
  aboleth.terrains = [ Terrain.find_by_name('Aquatic') ]
  giant_fire_beetle.terrains = [ Terrain.find_by_name('Aquatic'), Terrain.find_by_name('Deserts'),
                                 Terrain.find_by_name('Forests'), Terrain.find_by_name('Glaciers'),
                                 Terrain.find_by_name('Hills'), Terrain.find_by_name('Mountains'),
                                 Terrain.find_by_name('Plains'), Terrain.find_by_name('Ruins'),
                                 Terrain.find_by_name('Swamps/Marshes'), Terrain.find_by_name('Underground'),
                                 Terrain.find_by_name('Urban') ]
  phoenix.terrains = [ Terrain.find_by_name('Deserts'), Terrain.find_by_name('Hills') ]
  chupacabra.terrains = [ Terrain.find_by_name('Hills'), Terrain.find_by_name('Plains') ]
  frumious_bandersnatch.terrains = [ Terrain.find_by_name('Forests') ]
  flumph.terrains = [ Terrain.find_by_name('Deserts'), Terrain.find_by_name('Forests'),
                      Terrain.find_by_name('Glaciers'), Terrain.find_by_name('Hills'),
                      Terrain.find_by_name('Mountains'), Terrain.find_by_name('Plains'),
                      Terrain.find_by_name('Ruins'), Terrain.find_by_name('Swamps/Marshes'),
                      Terrain.find_by_name('Underground'), Terrain.find_by_name('Urban') ]
  lynx.terrains = [ Terrain.find_by_name('Forests'), Terrain.find_by_name('Hills'),
                    Terrain.find_by_name('Mountains'), Terrain.find_by_name('Plains') ]
  greenskin_orc.terrains = [ Terrain.find_by_name('Forests') ]
  goblin.terrains = [ Terrain.find_by_name('Forests'), Terrain.find_by_name('Plains') ]
  skeleton.terrains = [ Terrain.find_by_name('Aquatic'), Terrain.find_by_name('Deserts'),
                        Terrain.find_by_name('Forests'), Terrain.find_by_name('Glaciers'),
                        Terrain.find_by_name('Hills'), Terrain.find_by_name('Mountains'),
                        Terrain.find_by_name('Plains'), Terrain.find_by_name('Ruins'),
                        Terrain.find_by_name('Swamps/Marshes'), Terrain.find_by_name('Underground'),
                        Terrain.find_by_name('Urban') ]
  mummy.terrains = [ Terrain.find_by_name('Aquatic'), Terrain.find_by_name('Deserts'),
                     Terrain.find_by_name('Forests'), Terrain.find_by_name('Glaciers'),
                     Terrain.find_by_name('Hills'), Terrain.find_by_name('Mountains'),
                     Terrain.find_by_name('Plains'), Terrain.find_by_name('Ruins'),
                     Terrain.find_by_name('Swamps/Marshes'), Terrain.find_by_name('Underground'),
                     Terrain.find_by_name('Urban') ]
  zombie.terrains = [ Terrain.find_by_name('Aquatic'), Terrain.find_by_name('Deserts'),
                      Terrain.find_by_name('Forests'), Terrain.find_by_name('Glaciers'),
                      Terrain.find_by_name('Hills'), Terrain.find_by_name('Mountains'),
                      Terrain.find_by_name('Plains'), Terrain.find_by_name('Ruins'),
                      Terrain.find_by_name('Swamps/Marshes'), Terrain.find_by_name('Underground'),
                      Terrain.find_by_name('Urban') ]
  orcish_warclops.terrains = [ Terrain.find_by_name('Hills'), Terrain.find_by_name('Mountains'),
                               Terrain.find_by_name('Underground') ]
  lion.terrains = [ Terrain.find_by_name('Plains') ]
  leopard.terrains = [ Terrain.find_by_name('Forests') ]
  robot_golem.terrains = [ Terrain.find_by_name('Aquatic'), Terrain.find_by_name('Deserts'),
                           Terrain.find_by_name('Forests'), Terrain.find_by_name('Glaciers'),
                           Terrain.find_by_name('Hills'), Terrain.find_by_name('Mountains'),
                           Terrain.find_by_name('Plains'), Terrain.find_by_name('Ruins'),
                           Terrain.find_by_name('Swamps/Marshes'), Terrain.find_by_name('Underground'),
                           Terrain.find_by_name('Urban') ]
  barbtongued_wyvern.terrains = [ Terrain.find_by_name('Hills') ]
  mandragora.terrains = [ Terrain.find_by_name('Aquatic'), Terrain.find_by_name('Deserts'),
                          Terrain.find_by_name('Forests'), Terrain.find_by_name('Glaciers'),
                          Terrain.find_by_name('Hills'), Terrain.find_by_name('Mountains'),
                          Terrain.find_by_name('Plains'), Terrain.find_by_name('Ruins'),
                          Terrain.find_by_name('Swamps/Marshes'), Terrain.find_by_name('Underground'),
                          Terrain.find_by_name('Urban') ]
end
